project_id = "xxwdjfzcuudkxrbsjxto"

[functions.send-push-notification]
verify_jwt = false

[functions.match-contacts]
verify_jwt = true

[functions.send-bill-reminders]
verify_jwt = false

[functions.send-iou-reminders]
verify_jwt = false
